language: groovy
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.grails"
jdk:
- oraclejdk7
before_script:
- chmod +x grailsw
before_install:
- openssl aes-256-cbc -K $encrypted_dbb92d3b0e7c_key -iv $encrypted_dbb92d3b0e7c_iv
  -in grails-app/conf/riotapi.properties.enc -out grails-app/conf/riotapi.properties
  -d
script:
- "./grailsw refresh-dependencies"
- "./grailsw test-app -coverage -xml --stacktrace"

deploy:
  provider: heroku
  api_key:
    secure: AObmgWg18MygsmxltLC+3ssstCF+s+BKK57OGgiZQwnUMIqqbXb7S+Ho4gyemQB/il61nxdtcSVFOtPZVB3Y5gi50uFktgN6NzxWCZjk6r+o0znLW8uWuDR0rsnYb3NFZGpNjzPmc0SzaSJMY+JDpjq9R/flfymx3VW4Wawu7/cCXLyZld+HYn9iIPoKvryONDiNDKycEptxOJgkEcdDhhVTPdoBc7O2WKcNf3+SNEWY+FXlV8dfutG2eE30WDKPWRvLHXKcaeoVqPy8Vcft8YRcsHqBc2Kak92BhUixelioFkXRUJmD73U5rjCh20XZcjd5Go1gpfVJkMMM8ffKAt4kMQTI0xt+U31M1TsXkVCLZwMyIdPkNvHKuNeP7xBStM5SS7M84joLLSv4FmAwtS6pTo/7KayrgfQhjsTsSfKTForWmgQmQmsyG3+b1VP46ZPText/TyhmeMGaoHNJUO77m1nMao3FbXSOB3bcqonhmpiofCiJx9nE3HOMqEgjOZxuMXqMIfziFpKoze+j6Ms88vFOF+gJX7ZSF8pEmg/OYf9OTTa1pnJ0JhhNXcoCQb4mqlQGRzkfH9f7w0O3GF9mx/52iIo+Is3wfbi7+B9uUUG7xTj2P1IsordBCqk2gmBXeloAlPhwSHxB0wU25yCqll2FDaOiWbncOYdJt8o=
  app:
    pre-prod: project-crios