language: groovy

jdk:
- oraclejdk7

before_script:
- chmod +x grailsw

before_install:
- openssl aes-256-cbc -K $encrypted_dbb92d3b0e7c_key -iv $encrypted_dbb92d3b0e7c_iv
  -in riotapi.properties.enc -out riotapi.properties -d

script:
- ./grailsw refresh-dependencies
- ./grailsw test-app -coverage -xml --stacktrace

